spring:
  profiles:
    active: dev

  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: TEST
    password: 123456
 #指定端口,具体视自己情况而定,只要不重复就可以
  devtools:
    livereload:
      port: 35730

mybatis:
  type-aliases-package: com.qbwl.bkglpt.entity
# mapper.xml 文件路径
  mapper-locations: classpath:mapper/*.xml

#分页查询 Start
#helper-dialect：指定 数据库，不指定的话会默认自动检测数据库类型
#reasonable：是否启用分页合理化。如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；不启用的，以上两种情况都会返回空数据
#support-methods-arguments：默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。（copy来的，因为我也不知道怎么去解释）
#params：用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
pagehelper:
   helper-dialect: oracle
   reasonable: true
   support-methods-arguments: true
   params: pageSize
#分页查询 End



---
spring:
  profiles: dev

server:
  port: 83

logging:
  config: classpath:logConfig/logback-spring-dev.xml

---
spring:
  profiles: uat
logging:
  config: classpath:logConfig/logback-spring-uat.xml


---

spring:
  profiles: prod
logging:
  config: classpath:logConfig/logback-spring-prod.xml
